import Head from 'next/head'
import { CldImage } from '../../next-cloudinary';

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <ul className={styles.images}>
          <li>
            <CldImage
              width="600"
              height="600"
              src="dgtdceexujjgxy0wlwgn.jpg"
              layout="responsive"
              removeBackground
            />
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        Next.js ♥️ Cloudinary
      </footer>
    </div>
  )
}
