import Head from 'next/head'
import { CldImage } from '../../next-cloudinary';

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Cloudinary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          Next Cloudinary
        </h1>

        <ul className={styles.images}>
          <li>
            <CldImage
              width="1920"
              height="1200"
              src="images/turtle"
              layout="responsive"
            />
          </li>
          <li>
            <CldImage
              width="1920"
              height="1200"
              src="images/turtle"
              layout="responsive"
              removeBackground
            />
          </li>
          <li>
            <CldImage
              width="1920"
              height="1200"
              src="images/turtle"
              layout="responsive"
              removeBackground
              underlays={[{
                publicId: 'images/galaxy',
                width: 1920,
                height: 1200,
                crop: 'fill'
              }]}
            />
          </li>
          <li>
            <CldImage
              width="1920"
              height="1200"
              src="images/turtle"
              layout="responsive"
              removeBackground
              overlays={[{
                publicId: 'images/earth',
                position: {
                  x: 10,
                  y: 10,
                  gravity: 'north_west',
                },
                effects: [
                  {
                    crop: 'fill',
                    gravity: 'auto',
                    width: 500,
                    height: 500
                  }
                ]
              }]}
            />
          </li>
          <li>
            <CldImage
              width="2670"
              height="1782"
              src="images/sneakers"
              layout="responsive"
              removeBackground
              overlays={[{
                width: 2670 - 20,
                crop: 'fit',
                position: {
                  x: 10,
                  y: 10,
                  gravity: 'north_west',
                },
                text: {
                  color: 'blueviolet',
                  fontFamily: 'Source Sans Pro',
                  fontSize: 120,
                  fontWeight: 'bold',
                  textDecoration: 'underline',
                  letterSpacing: 14,
                  text: 'Cool Beans'
                }
              }]}
            />
          </li>
        </ul>
      </main>
    </div>
  )
}
