import Head from 'next/head'
import { CldImage } from '../../next-cloudinary';

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Cloudinary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          Next Cloudinary
        </h1>

        <h2>Effects</h2>

        <ul className={styles.images}>
          <li>
            <CldImage
              width="1920"
              height="1200"
              src="images/turtle"
              layout="responsive"
              removeBackground
            />
            <h3 className={styles.imageTitle}>
              Background Removal
            </h3>
            <pre><code>{`removeBackground`}</code></pre>
          </li>

        </ul>

        <h2>Placeholders</h2>

        <ul className={styles.images}>
          <li>
            <CldImage
              width="1920"
              height="1200"
              src="images/turtle"
              layout="responsive"
              placeholder="blur"
            />
            <h3 className={styles.imageTitle}>
              Blur
            </h3>
            <pre><code>{`placeholder="blur"`}</code></pre>
          </li>
          <li>
            <CldImage
              width="1920"
              height="1200"
              src="images/turtle"
              layout="responsive"
              placeholder="grayscale"
            />
            <h3 className={styles.imageTitle}>
              Grayscale
            </h3>
            <pre><code>{`placeholder="grayscale"`}</code></pre>
          </li>
          <li>
            <CldImage
              width="1920"
              height="1200"
              src="images/turtle"
              layout="responsive"
              placeholder="color:blueviolet"
            />
            <h3 className={styles.imageTitle}>
              Color
            </h3>
            <pre><code>{`placeholder="color:blueviolet"`}</code></pre>
          </li>
        </ul>

        <h2>Image Overlays</h2>

        <ul className={styles.images}>
          <li>
            <CldImage
              width="1920"
              height="1200"
              src="images/turtle"
              layout="responsive"
              overlays={[{
                publicId: 'images/earth',
                position: {
                  x: 50,
                  y: 50,
                  gravity: 'north_west',
                },
                effects: [
                  {
                    crop: 'fill',
                    gravity: 'auto',
                    width: 500,
                    height: 500
                  }
                ]
              }]}
            />
            <h3 className={styles.imageTitle}>
              Overlay Image by Public ID
            </h3>
            <pre><code>{`overlays={[{
  publicId: 'images/earth',
  position: {
    x: 10,
    y: 10,
    gravity: 'north_west',
  },
  effects: [
    {
      crop: 'fill',
      gravity: 'auto',
      width: 500,
      height: 500
    }
  ]
}]}`}</code></pre>
          </li>
        </ul>

        <h2>Image Underlays</h2>

        <ul className={styles.images}>
          <li>
            <CldImage
              width="1920"
              height="1200"
              src="images/turtle"
              layout="responsive"
              removeBackground
              underlays={[{
                publicId: 'images/galaxy',
                width: 1920,
                height: 1200,
                crop: 'fill'
              }]}
            />
            <h3 className={styles.imageTitle}>
              Background Removal with Underlay
            </h3>
            <pre><code>{`removeBackground
underlays={[{
  publicId: 'images/galaxy',
  width: 1920,
  height: 1200,
  crop: 'fill'
}]}`}</code></pre>
          </li>
        </ul>

        <h2>Text Overlays</h2>

        <ul className={styles.images}>
          <li>
            <CldImage
              width="2670"
              height="1782"
              src="images/sneakers"
              layout="responsive"
              overlays={[{
                width: 2670 - 20,
                crop: 'fit',
                position: {
                  x: 140,
                  y: 140,
                  angle: -20,
                  gravity: 'south_east',
                },
                text: {
                  color: 'blueviolet',
                  fontFamily: 'Source Sans Pro',
                  fontSize: 250,
                  fontWeight: 'bold',
                  textDecoration: 'underline',
                  letterSpacing: 14,
                  text: 'Cool Beans'
                }
              }]}
            />
            <h3 className={styles.imageTitle}>
              Text Overlay
            </h3>
            <pre><code>{`overlays={[{
  width: 2670 - 20,
  crop: 'fit',
  position: {
    x: 10,
    y: 10,
    gravity: 'north_west',
  },
  text: {
    color: 'blueviolet',
    fontFamily: 'Source Sans Pro',
    fontSize: 120,
    fontWeight: 'bold',
    textDecoration: 'underline',
    letterSpacing: 14,
    text: 'Cool Beans'
  }
}]}`}</code></pre>
          </li>
        </ul>
      </main>
    </div>
  )
}
